FROM ubuntu:22.04

WORKDIR /home
SHELL [ "/bin/bash", "-c" ]

ENV GOPATH=/usr/local/go/bin
ENV RUSTPATH=/root/.cargo/bin
ENV LLVM_HOME=/home/LLVM-19.1.7-Linux-X64
ENV PATH=$GOPATH:$RUSTPATH:${LLVM_HOME}/bin:$PATH
ENV TZ=Asia/Shanghai
ENV LIBTORCH_USE_PYTORCH=1
ENV LD_LIBRARY_PATH=/usr/local/lib/python3.10/dist-packages/torch/lib

# Download following files to the tools/syz-meta/docker and build the image by COPY command will save time:
# go1.23.6.linux-amd64.tar.gz, LLVM-19.1.7-Linux-X64.tar.xz, v2.0.8.tar.gz (flatbuffers-v2.0.8)
COPY go1.23.6.linux-amd64.tar.gz LLVM-19.1.7-Linux-X64.tar.xz v2.0.8.tar.gz /home/
COPY mock.patch /home/

# Install basic packages
# TODO: Some packages can be removed to reduce image size
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
RUN apt-get install -y sudo wget curl git vim build-essential make gcc g++ flex bison bc debootstrap
RUN apt-get install -y qemu-system-x86 xz-utils cmake gdb libdw-dev libssl-dev sqlite3 libsqlite3-dev
RUN apt-get install -y python3 python3-pip python3-dev language-pack-en-base rsync file openssh-server
RUN apt-get install -y dwarves unzip libssl-dev pkg-config

# Install python packages
# MOCK can boost model training via CUDA by using tch-rs. But, until 2025-09, the tch-rs only supports
# pytorch <= 2.7.0. Our CUDA version is 12.9, corresponding pytorch is 2.8.0. So we use CPU instead GPU.
RUN pip install numpy django
RUN pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cpu

# Install golang-1.23.6
RUN wget -nc https://go.dev/dl/go1.23.6.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.23.6.linux-amd64.tar.gz && \
    rm go1.23.6.linux-amd64.tar.gz

# Install LLVM-19.1.7 (binary)
RUN wget -nc https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-Linux-X64.tar.xz && \
    tar -xvf LLVM-19.1.7-Linux-X64.tar.xz && \
    rm LLVM-19.1.7-Linux-X64.tar.xz

# Install flatbuffers-2.0.8
RUN wget -nc https://github.com/google/flatbuffers/archive/refs/tags/v2.0.8.tar.gz && \
    tar -xzvf v2.0.8.tar.gz && \
    pushd flatbuffers-2.0.8 && \
    cmake -G "Unix Makefiles" && \
    make -j && \
    make install && \
    popd && \
    rm -rf v2.0.8.tar.gz

# Install rust 1.90.0
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN rustup default 1.90.0

# Download, patch, and build MOCK
RUN git clone https://github.com/m0ck1ng/mock && \
    cd mock && \
    git checkout 8f68fe365d7eb17ce354c8fc8ec7ff9a320080df
RUN cd mock && \
    git apply /home/mock.patch
RUN cd mock && \
    cargo build --release
