FROM ubuntu:22.04

WORKDIR /home
SHELL [ "/bin/bash", "-c" ]

ENV GOPATH=/usr/local/go/bin
ENV LLVM_HOME=/home/LLVM-19.1.7-Linux-X64
ENV PATH=$GOPATH:${LLVM_HOME}/bin:$PATH
ENV TZ=Asia/Shanghai

# Download following files to the tools/syz-meta/docker and build the image by COPY command will save time:
# go1.23.6.linux-amd64.tar.gz, v2.0.8.tar.gz (flatbuffers-v2.0.8)
COPY go1.23.6.linux-amd64.tar.gz LLVM-19.1.7-Linux-X64.tar.xz v2.0.8.tar.gz /home/

# Install basic packages
# TODO: Some packages can be removed to reduce image size
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
RUN apt-get install -y sudo wget curl git vim build-essential make gcc g++ flex bison bc debootstrap
RUN apt-get install -y qemu-system-x86 xz-utils cmake gdb libdw-dev libssl-dev sqlite3 libsqlite3-dev
RUN apt-get install -y python3 python3-pip python3-dev language-pack-en-base rsync file openssh-server
RUN apt-get install -y libelf-dev lsb-release software-properties-common gnupg dwarves unzip

# Install LLVM-19.1.7 (binary)
RUN wget -nc https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-Linux-X64.tar.xz && \
    tar -xvf LLVM-19.1.7-Linux-X64.tar.xz && \
    rm LLVM-19.1.7-Linux-X64.tar.xz

# Install LLVM-14 and LLVM-15 for building ACTOR and kernel analyzing
RUN wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    sudo ./llvm.sh 14 && \
    sudo ./llvm.sh 15

# Install golang-1.23.6
RUN wget -nc https://go.dev/dl/go1.23.6.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.23.6.linux-amd64.tar.gz && \
    rm go1.23.6.linux-amd64.tar.gz

# Install flatbuffers-2.0.8
RUN wget -nc https://github.com/google/flatbuffers/archive/refs/tags/v2.0.8.tar.gz && \
    tar -xzvf v2.0.8.tar.gz && \
    pushd flatbuffers-2.0.8 && \
    cmake -G "Unix Makefiles" && \
    make -j && \
    make install && \
    popd && \
    rm -rf v2.0.8.tar.gz

# Download ACTOR && build ACTOR
RUN git clone https://github.com/ucsb-seclab/actor && \
    cd actor && \
    git checkout 918665bf05acb2663a4b3f48a98e48f7f09aa908
RUN cd actor/semantic-inference && \
    echo 'clang-14 -g -fexperimental-new-pass-manager -fpass-plugin=/home/actor/semantic-inference/build/libktypesPass.so "$@"' > clang-ktypes-14 && \
    echo 'clang-15 -g -fexperimental-new-pass-manager -fpass-plugin=/home/actor/semantic-inference/build/libktypesPass.so "$@"' > clang-ktypes-15 && \
    ln -s /home/actor/semantic-inference/clang-ktypes-14 /usr/local/bin/clang-ktypes-14 && \
    ln -s /home/actor/semantic-inference/clang-ktypes-15 /usr/local/bin/clang-ktypes-15
