FROM ubuntu:22.04

WORKDIR /home
SHELL [ "/bin/bash", "-c" ]

ENV GOPATH=/usr/local/go/bin
ENV LLVM_HOME=/home/LLVM-19.1.7-Linux-X64
ENV PATH=$GOPATH:${LLVM_HOME}/bin:$PATH
ENV TZ=Asia/Shanghai

# Download following files to the docker/ and build the image by COPY command will save time:
# wget -P docker https://go.dev/dl/go1.23.6.linux-amd64.tar.gz
# wget -P docker https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-Linux-X64.tar.xz
# wget -P docker https://github.com/google/flatbuffers/archive/refs/tags/v2.0.8.tar.gz
COPY go1.23.6.linux-amd64.tar.gz LLVM-19.1.7-Linux-X64.tar.xz v2.0.8.tar.gz /home/

# Install basic packages
# TODO: Some packages can be removed to reduce image size
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
RUN apt-get install -y sudo wget curl git vim build-essential make gcc g++ flex bison bc debootstrap
RUN apt-get install -y qemu-system-x86 xz-utils cmake gdb libdw-dev libssl-dev sqlite3 libsqlite3-dev
RUN apt-get install -y python3 python3-pip python3-dev language-pack-en-base rsync file devscripts equivs
RUN apt-get install -y config-package-dev debhelper-compat adb fastboot libncurses5 cloc openssh-server
RUN apt-get install -y dwarves unzip gettext ccache git-email

# Install python packages
RUN pip install dotenv chromadb GitPython marko clang==19.1.7 google-genai isort unstructured markdown
RUN pip install langchain-text-splitters langchain-community langgraph langchain-core langchain-openai
RUN pip install langchain-google-genai langchain-chroma docutils anthropic plotly kaleido
RUN plotly_get_chrome -y

# Install golang-1.23.6
RUN tar -C /usr/local -xzf go1.23.6.linux-amd64.tar.gz && \
    rm go1.23.6.linux-amd64.tar.gz

# Install LLVM-19.1.7 (binary)
RUN tar -xvf LLVM-19.1.7-Linux-X64.tar.xz && \
    rm LLVM-19.1.7-Linux-X64.tar.xz

# Install flatbuffers-2.0.8
RUN tar -xzvf v2.0.8.tar.gz && \
    pushd flatbuffers-2.0.8 && \
    cmake -G "Unix Makefiles" && \
    make -j && \
    make install && \
    popd && \
    rm -rf v2.0.8.tar.gz