FROM ubuntu:22.04

WORKDIR /home
SHELL [ "/bin/bash", "-c" ]

ARG VERSION=v1.15.0

ENV TZ=Asia/Shanghai

# Copy patch
COPY cuttlefish.patch /home/cuttlefish.patch

# Install basic packages
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
RUN apt-get install -y git devscripts equivs config-package-dev debhelper-compat golang curl

# Install Vulkan-related packages to boost performance of cuttlefish virtual device
RUN apt-get install -y vulkan-tools libegl1-mesa libegl1 libgles2-mesa libgles2 libvulkan1

# Create necessary groups
RUN groupadd --system kvm || true
RUN groupadd --system cvdnetwork || true
RUN groupadd --system render || true

# Install repo
RUN curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/bin/repo && \
    chmod a+x /usr/bin/repo

# Install android-cuttlefish
RUN git clone https://github.com/google/android-cuttlefish
WORKDIR /home/android-cuttlefish
RUN git checkout ${VERSION} && \
    git apply cuttlefish.patch
RUN tools/buildutils/installbazel.sh
RUN tools/buildutils/build_packages.sh
RUN dpkg -i ./cuttlefish-base_*_*64.deb || apt-get install -f -y
RUN dpkg -i ./cuttlefish-user_*_*64.deb || apt-get install -f -y
RUN usermod -aG kvm,cvdnetwork,render root

WORKDIR /