#############################
### General configuration ###
#############################
x-base: &base
  privileged: true
  network_mode: host
  environment: &env
    KERNEL_OBJ: /vol/android/common-android14-6.1/dist
    KERNEL_SRC: /vol/android/common-android14-6.1/common
    IMAGE: /vol/android/android14-gsi
    TARGET: aosp_cf_x86_64_phone-userdebug
    SYZMETA: /vol/SyzMeta
    SYZKALLER: /vol/syzkaller
  volumes:
    - /mnt/d/volumes/kernel-fuzzing:/vol
    - $PWD/volumes/kernel-fuzzing/common-android14-6.1:/vol2
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro

###################################
### Preprocessing configuration ###
###################################
x-preprocessing-base: &preprocessing-base
  <<: *base
  image: syzmeta:latest
  cpus: 1
  environment:
    <<: *env
    EMAIL: "radon@xs.ustb.edu.cn"
    MRDIR: /vol/SyzMeta/workdir/MRs/android/common-android14-6.1
    CORPUS: /vol/SyzMeta/workdir/external-corpus

################################
### Cuttlefish configuration ###
################################
x-cvd-base: &cvd-base
  <<: *base
  image: cuttlefish:v1.15.0

#############################
### Fuzzing configuration ###
#############################
x-syzmeta-base: &syzmeta-base
  <<: *base
  image: syzmeta:latest
  cpus: 2
  environment: &syzmeta-env
    <<: *env

x-syzkaller-base: &syzkaller-base
  <<: *base
  image: syzkaller:latest
  cpus: 2
  environment: &syzkaller-env
    <<: *env

x-moonshine-base: &moonshine-base
  <<: *base
  image: moonshine:latest
  cpus: 2
  environment: &moonshine-env
    <<: *env

####################
### Project name ###
####################
name: common-android14-6_1

services:
  # Identify kernel MRs
  iden:
    <<: *preprocessing-base
    profiles:
      - iden
    command: |
      bash -c '
        cd $$SYZMETA &&
        python3 -u src/experiment.py \
          --email $$EMAIL \
          iden --specdir \
          $$MRDIR --corpus \
          $$CORPUS > iden-common-android14-6.1.log 2>&1
      '

  # Implement identified MRs
  impl:
    <<: *preprocessing-base
    cpus: 4
    profiles:
      - impl
    command: >
      bash -c '
        cd $$SYZMETA &&
        python3 -u src/experiment.py \
          --email $$EMAIL \
          impl \
          --idendir $$MRDIR \
          --syzkaller $$SYZKALLER > impl-common-android14-6.1.log 2>&1
      '

  # Evaluate quality encoded-MRs
  eval:
    <<: *preprocessing-base
    cpus: 4
    profiles:
      - eval
    command: |
      bash -c '
        cd $$SYZMETA &&
        python3 -u src/experiment.py \
          --email $$EMAIL \
          android_eval \
          --impldir $$MRDIR \
          --syzkaller $$SYZKALLER \
          --kernel_obj $$KERNEL_OBJ \
          --device 0.0.0.0:6520 > eval-common-android14-6.1.log 2>&1
      '

  run-cvd-for-eval:
    <<: *cvd-base
    cpus: 4
    image: cuttlefish:v1.15.0
    profiles:
      - cvd-for-eval
    command: |
      bash -c '
        cd $$IMAGE &&
        source build/envsetup.sh &&
        lunch $$TARGET &&
        yes | launch_cvd -daemon \
          -kernel_path=$$KERNEL_OBJ/bzImage \
          -initramfs_path=$$KERNEL_OBJ/initramfs.img \
          -resume=false &&
        LAUNCH_CVD_PID=$(pgrep -f launch_cvd) &&
        tail --pid=$$LAUNCH_CVD_PID -f /dev/null
      '

  # Boot Android virtual devices
  run-cvd-for-fuzz:
    <<: *cvd-base
    cpus: 20
    profiles:
      - cvd-for-fuzz
    command: |
      bash -c '
        cd $$IMAGE &&
        source build/envsetup.sh &&
        lunch $$TARGET &&
        yes | launch_cvd -daemon \
          -kernel_path=$$KERNEL_OBJ/bzImage \
          -initramfs_path=$$KERNEL_OBJ/initramfs.img \
          -resume=false \
          -num_instances=10 &&
        LAUNCH_CVD_PID=$(pgrep -f launch_cvd) &&
        tail --pid=$$LAUNCH_CVD_PID -f /dev/null
      '

  # Fuzzing via SyzMeta
  SyzMeta-000:
    <<: *syzmeta-base
    environment:
      <<: *syzmeta-env
      SERVADDR: 127.0.0.1:50000 # <- Please ensure this port is not used by other services since we use host networking
      WORKDIR: /vol2/SyzMeta/out-000
      SYZKALLER: /vol/SyzMeta/syzkaller
      DEVICE: 0.0.0.0:6520 # <- Please ensure this virtual device is not used by other services
    profiles:
      - syzmeta
    command: |
      bash -c '
        cat $$SYZMETA/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        $$SYZKALLER/bin/syz-manager -config /home/android.cfg > $$WORKDIR/SyzMeta.log 2>&1
      '

  SyzMeta-001:
    <<: *syzmeta-base
    environment:
      <<: *syzmeta-env
      SERVADDR: 127.0.0.1:50001 # <- Please ensure this port is not used by other services since we use host networking
      WORKDIR: /vol2/SyzMeta/out-001
      SYZKALLER: /vol/SyzMeta/syzkaller
      DEVICE: 0.0.0.0:6521 # <- Please ensure this virtual device is not used by other services
    profiles:
      - syzmeta
    command: |
      bash -c '
        cat $$SYZMETA/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        $$SYZMETA/syzkaller/bin/syz-manager -config /home/android.cfg > $$WORKDIR/SyzMeta.log 2>&1
      '

  SyzMeta-002:
    <<: *syzmeta-base
    environment:
      <<: *syzmeta-env
      SERVADDR: 127.0.0.1:50002 # <- Please ensure this port is not used by other services since we use host networking
      WORKDIR: /vol2/SyzMeta/out-002
      SYZKALLER: /vol/SyzMeta/syzkaller
      DEVICE: 0.0.0.0:6522 # <- Please ensure this virtual device is not used by other services
    profiles:
      - syzmeta
    command: |
      bash -c '
        cat $$SYZMETA/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        $$SYZMETA/syzkaller/bin/syz-manager -config /home/android.cfg > $$WORKDIR/SyzMeta.log 2>&1
      '

  SyzMeta-003:
    <<: *syzmeta-base
    environment:
      <<: *syzmeta-env
      SERVADDR: 127.0.0.1:50003 # <- Please ensure this port is not used by other services since we use host networking
      WORKDIR: /vol2/SyzMeta/out-003
      SYZKALLER: /vol/SyzMeta/syzkaller
      DEVICE: 0.0.0.0:6523 # <- Please ensure this virtual device is not used by other services
    profiles:
      - syzmeta
    command: |
      bash -c '
        cat $$SYZMETA/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        $$SYZKALLER/bin/syz-manager -config /home/android.cfg > $$WORKDIR/SyzMeta.log 2>&1
      '

  SyzMeta-004:
    <<: *syzmeta-base
    environment:
      <<: *syzmeta-env
      SERVADDR: 127.0.0.1:50004 # <- Please ensure this port is not used by other services since we use host networking
      WORKDIR: /vol2/SyzMeta/out-004
      SYZKALLER: /vol/SyzMeta/syzkaller
      DEVICE: 0.0.0.0:6524 # <- Please ensure this virtual device is not used by other services
    profiles:
      - syzmeta
    command: |
      bash -c '
        cat $$SYZMETA/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        $$SYZKALLER/bin/syz-manager -config /home/android.cfg > $$WORKDIR/SyzMeta.log 2>&1
      '

  # Fuzzing via syzkaller
  syzkaller-000:
    <<: *syzkaller-base
    environment:
      <<: *syzkaller-env
      SERVADDR: 127.0.0.1:50005 # <- Please ensure this port is not used by other services since we use host networking
      WORKDIR: /vol2/syzkaller/out-000
      DEVICE: 0.0.0.0:6525 # <- Please ensure this virtual device is not used by other services
    profiles:
      - syzkaller
    command: |
      bash -c '
        cat $$SYZMETA/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        $$SYZKALLER/bin/syz-manager -config /home/android.cfg > $$WORKDIR/syzkaller.log 2>&1
      '

  syzkaller-001:
    <<: *syzkaller-base
    environment:
      <<: *syzkaller-env
      SERVADDR: 127.0.0.1:50006 # <- Please ensure this port is not used by other services since we use host networking
      WORKDIR: /vol2/syzkaller/out-001
      DEVICE: 0.0.0.0:6526 # <- Please ensure this virtual device is not used by other services
    profiles:
      - syzkaller
    command: |
      bash -c '
        cat $$SYZMETA/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        $$SYZKALLER/bin/syz-manager -config /home/android.cfg > $$WORKDIR/syzkaller.log 2>&1
      '

  syzkaller-002:
    <<: *syzkaller-base
    environment:
      <<: *syzkaller-env
      SERVADDR: 127.0.0.1:50007 # <- Please ensure this port is not used by other services since we use host networking
      WORKDIR: /vol2/syzkaller/out-002
      DEVICE: 0.0.0.0:6527 # <- Please ensure this virtual device is not used by other services
    profiles:
      - syzkaller
    command: >
      bash -c "
        cat $$SYZMETA/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        $$SYZKALLER/bin/syz-manager -config /home/android.cfg > $$WORKDIR/syzkaller.log 2>&1
      "

  syzkaller-003:
    <<: *syzkaller-base
    environment:
      <<: *syzkaller-env
      SERVADDR: 127.0.0.1:50008 # <- Please ensure this port is not used by other services since we use host networking
      WORKDIR: /vol2/syzkaller/out-003
      DEVICE: 0.0.0.0:6528 # <- Please ensure this virtual device is not used by other services
    profiles:
      - syzkaller
    command: |
      bash -c '
        cat $$SYZMETA/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        $$SYZKALLER/bin/syz-manager -config /home/android.cfg > $$WORKDIR/syzkaller.log 2>&1
      '

  syzkaller-004:
    <<: *syzkaller-base
    environment:
      <<: *syzkaller-env
      SERVADDR: 127.0.0.1:50009 # <- Please ensure this port is not used by other services since we use host networking
      WORKDIR: /vol2/syzkaller/out-004
      DEVICE: 0.0.0.0:6529 # <- Please ensure this virtual device is not used by other services
    profiles:
      - syzkaller
    command: |
      bash -c '
        cat $$SYZMETA/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        $$SYZKALLER/bin/syz-manager -config /home/android.cfg > $$WORKDIR/syzkaller.log 2>&1
      '

  moonshine-000:
    <<: *moonshine-base
    environment:
      <<: *moonshine-env
      SERVADDR: 127.0.0.1:50010 # <- Please ensure this port is not used by other services since we use host networking
      WORKDIR: /vol2/moonshine/out-000
      DEVICE: 0.0.0.0:6525 # <- Please ensure this virtual device is not used by other services
    profiles:
      - moonshine
    command: |
      bash -c '
        cat $$SYZMETA/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        cp $$MOONSHINE/corpus.db $$WORKDIR/ &&
        $$SYZKALLER/bin/syz-manager -config /home/android.cfg > $$WORKDIR/moonshine.log 2>&1
      '

  moonshine-001:
    <<: *moonshine-base
    environment:
      <<: *moonshine-env
      SERVADDR: 127.0.0.1:50011 # <- Please ensure this port is not used by other services since we use host networking
      WORKDIR: /vol2/moonshine/out-001
      DEVICE: 0.0.0.0:6526 # <- Please ensure this virtual device is not used by other services
    profiles:
      - moonshine
    command: |
      bash -c '
        cat $$SYZMETA/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        cp $$MOONSHINE/corpus.db $$WORKDIR/ &&
        $$SYZKALLER/bin/syz-manager -config /home/android.cfg > $$WORKDIR/moonshine.log 2>&1
      '

  moonshine-002:
    <<: *moonshine-base
    environment:
      <<: *moonshine-env
      SERVADDR: 127.0.0.1:50012 # <- Please ensure this port is not used by other services since we use host networking
      WORKDIR: /vol2/moonshine/out-002
      DEVICE: 0.0.0.0:6527 # <- Please ensure this virtual device is not used by other services
    profiles:
      - moonshine
    command: |
      bash -c '
        cat $$SYZMETA/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        cp $$MOONSHINE/corpus.db $$WORKDIR/ &&
        $$SYZKALLER/bin/syz-manager -config /home/android.cfg > $$WORKDIR/moonshine.log 2>&1
      '

  moonshine-003:
    <<: *moonshine-base
    environment:
      <<: *moonshine-env
      SERVADDR: 127.0.0.1:50013 # <- Please ensure this port is not used by other services since we use host networking
      WORKDIR: /vol2/moonshine/out-003
      DEVICE: 0.0.0.0:6528 # <- Please ensure this virtual device is not used by other services
    profiles:
      - moonshine
    command: |
      bash -c '
        cat $$SYZMETA/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        cp $$MOONSHINE/corpus.db $$WORKDIR/ &&
        $$SYZKALLER/bin/syz-manager -config /home/android.cfg > $$WORKDIR/moonshine.log 2>&1
      '

  moonshine-004:
    <<: *moonshine-base
    environment:
      <<: *moonshine-env
      SERVADDR: 127.0.0.1:50014 # <- Please ensure this port is not used by other services since we use host networking
      WORKDIR: /vol2/moonshine/out-004
      DEVICE: 0.0.0.0:6529 # <- Please ensure this virtual device is not used by other services
    profiles:
      - moonshine
    command: |
      bash -c '
        cat $$SYZMETA/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        cp $$MOONSHINE/corpus.db $$WORKDIR/ &&
        $$SYZKALLER/bin/syz-manager -config /home/android.cfg > $$WORKDIR/moonshine.log 2>&1
      '
