####################
### Project name ###
####################
name: misc

services:

  # Usage: modify environment variables according your situation and run `docker-compose -f compose.misc.yaml up bisect -d`
  bisect:
    privileged: true
    cpus: 8
    environment:
      COMPILER: gcc
      BIN_DIR: /vol2/bisect_bin
      KERNEL: /vol/linux/bisect/mainline
      IMAGE: /vol/images/Debian
      SYZMETA: /vol/SyzMeta
      VMCOUNT: 4
      WORKDIR: /vol2/bisect
      CRASH: /vol2/bisect/crash
    volumes:
      - /mnt/d/volumes/kernel-fuzzing:/vol
      - $PWD/volumes/kernel-fuzzing/bisect:/vol2
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    image: syzmeta:latest
    command: |
      bash -c '
        mkdir -p /home/go/src/github.com/Radon10043/
        cp -r $$SYZMETA /home/go/src/github.com/Radon10043/
        cat $$SYZMETA/configs/fuzz/linux.cfg | envsubst > /home/bisect.cfg
        $$SYZMETA/syzkaller/bin/syz-bisect -config=/home/bisect.cfg -crash=$$CRASH > $$WORKDIR/bisect.log 2>&1
      '
