# Usage: docker compose -f $THIS_FILE up $SERVICE --scale $SERVICE=$NUM_INSTANCE -d

#############################
### General configuration ###
#############################
x-base: &base
  privileged: true
  cpuset: "0-19"
  cpus: "2"
  environment: &env
    KERNEL: /vol/linux/v6.6.100
    IMAGE: /vol/images/Debian
    VMCOUNT: 1
    MYFUZZ: /vol/myfuzz
    SYZKALLER: /vol/syzkaller
    MOONSHINE: /vol/moonshine
    HEALER: /vol/healer
    MOCK: /vol/mock
    ACTOR: /vol/actor
  volumes:
    - /mnt/d/volumes/kernel-fuzzing:/vol
    - $PWD/volumes/kernel-fuzzing/linux-v6.6.100:/vol2
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro

####################
### Project name ###
####################
name: linux-6_6_100

services:
  iden:
    <<: *base
    image: myfuzz:latest
    cpus: 2
    network_mode: host
    environment:
      <<: *env
      EMAIL: ""
      CORPUS: /vol/myfuzz/workdir/external-corpus
      MRDIR: /vol/myfuzz/workdir/MRs/linux/v6.6.100
    command: |
      bash -c '
        cd $$SYZMETA &&
        python3 -u src/experiment.py \
          --email $$EMAIL \
          iden \
          --specdir $$MRDIR \
          --corpus $$CORPUS > iden-linux.v6.6.100.log 2>&1
      '

  impl:
    <<: *base
    image: myfuzz:latest
    cpus: 16
    network_mode: host
    environment:
      <<: *env
      SYZKALLER: /vol/syzkaller-dirty
      EMAIL: ""
      MRDIR: /vol/myfuzz/workdir/MRs-woRAG/linux/v6.6.100
      http_proxy: ""
      https_proxy: ""
    command: >
      bash -c '
        cd $$MYFUZZ &&
        python3 -u src/experiment.py \
          --email $$EMAIL \
          impl \
          --idendir $$MRDIR \
          --syzkaller $$SYZKALLER > impl-woRAG-linux.v6.6.100.log 2>&1
      '

  eval:
    <<: *base
    image: myfuzz:latest
    cpus: 16
    network_mode: host
    environment:
      <<: *env
      SYZKALLER: /vol/syzkaller-dirty
      EMAIL: ""
      MRDIR: /vol/myfuzz/workdir/MRs-woRAG/linux/v6.6.100
    command: |
      bash -c '
        cd $$MYFUZZ &&
        python3 -u src/experiment.py \
          --email $$EMAIL \
          eval \
          --impldir $$MRDIR \
          --syzkaller $$SYZKALLER \
          --kernel_obj $$KERNEL \
          --kernel_typ linux \
          --image_obj $$IMAGE > eval-woRAG-linux.v6.6.100.log 2>&1
      '

  myfuzz:
    <<: *base
    image: myfuzz:latest
    environment:
      <<: *env
      SYZKALLER: /vol/myfuzz/syzkaller
      OUT_ROOT: /vol2/myfuzz
    command: |
      bash -c '
        export suffix=$$(cat /proc/sys/kernel/random/uuid | cut -d- -f1)
        export WORKDIR=$$OUT_ROOT/out-$$suffix
        mkdir -p $$WORKDIR &&
        cat $$MYFUZZ/configs/fuzz/linux.cfg | envsubst > /home/linux.cfg &&
        timeout -s KILL 24h $$MYFUZZ/syzkaller/bin/syz-manager -config /home/linux.cfg > $$WORKDIR/myfuzz.log 2>&1
      '

  syzkaller:
    <<: *base
    image: syzkaller:latest
    environment:
      <<: *env
      OUT_ROOT: /vol2/syzkaller/
    command: |
      bash -c '
        export suffix=$$(cat /proc/sys/kernel/random/uuid | cut -d- -f1)
        export WORKDIR=$$OUT_ROOT/out-$$suffix
        mkdir -p $$WORKDIR &&
        cat $$MYFUZZ/configs/fuzz/linux.cfg | envsubst > /home/linux.cfg &&
        timeout -s KILL 24h $$SYZKALLER/bin/syz-manager -config /home/linux.cfg > $$WORKDIR/syzkaller.log 2>&1
      '

  moonshine:
    <<: *base
    image: moonshine:latest
    environment:
      <<: *env
      OUT_ROOT: /vol2/moonshine
    command: |
      bash -c '
        export suffix=$$(cat /proc/sys/kernel/random/uuid | cut -d- -f1)
        export WORKDIR=$$OUT_ROOT/out-$$suffix
        cat $$MYFUZZ/configs/fuzz/linux.cfg | envsubst > /home/linux.cfg &&
        mkdir -p $$WORKDIR &&
        cp $$MOONSHINE/corpus.db $$WORKDIR/ &&
        timeout -s KILL 24h $$SYZKALLER/bin/syz-manager -config /home/linux.cfg > $$WORKDIR/moonshine.log 2>&1
      '

  healer:
    <<: *base
    image: healer:latest
    environment:
      <<: *env
      OUT_ROOT: /vol2/healer
    command: |
      bash -c '
        export suffix=$$(cat /proc/sys/kernel/random/uuid | cut -d- -f1)
        export WORKDIR=$$OUT_ROOT/out-$$suffix
        mkdir -p $$WORKDIR &&
        cd $$HEALER/target/release &&
        timeout -s KILL 24h ./healer \
          -k $$KERNEL/arch/x86/boot/bzImage \
          -d $$IMAGE/bullseye.img \
          --ssh-key $$IMAGE/bullseye.id_rsa \
          -j 1 \
          --disable-repro \
          -o $$WORKDIR > $$WORKDIR/healer.log 2>&1
      '

  mock:
    <<: *base
    image: mock:latest
    environment:
      <<: *env
      OUT_ROOT: /vol2/mock
    command: |
      bash -c '
        export suffix=$$(cat /proc/sys/kernel/random/uuid | cut -d- -f1)
        export WORKDIR=$$OUT_ROOT/out-$$suffix
        mkdir -p $$WORKDIR
        cd $$MOCK/tools/model_manager
        python3 manage.py runserver &
        cd $$MOCK/target/release &&
        timeout -s KILL 24h ./healer \
          -k $$KERNEL/arch/x86/boot/bzImage \
          -d $$IMAGE/bullseye.img \
          --ssh-key $$IMAGE/bullseye.id_rsa \
          -j 1 \
          --disable-repro \
          -o $$WORKDIR > $$WORKDIR/mock.log 2>&1
      '

  actor:
    <<: *base
    image: actor:latest
    environment:
      <<: *env
      OUT_ROOT: /vol2/actor
      KERNEL: /vol/linux/v6.6.100.actor
      IMAGE: /vol/images/Debian-for-actor-v6.6.100
    command: |
      bash -c '
        export suffix=$$(cat /proc/sys/kernel/random/uuid | cut -d- -f1)
        export WORKDIR=$$OUT_ROOT/out-$$suffix
        mkdir -p $$WORKDIR &&
        cp $$MYFUZZ/data/actor/ptrs.v6.6.100.txt $$WORKDIR/ptrs.txt &&
        cat $$MYFUZZ/configs/fuzz/linux.actor.cfg | envsubst > /home/linux.cfg &&
        timeout -s KILL 24h $$ACTOR/src/github.com/google/syzkaller/bin/syz-manager -config=/home/linux.cfg > $$WORKDIR/actor.log 2>&1
      '

  myfuzz-E-:
    <<: *base
    image: myfuzz:latest
    environment:
      <<: *env
      SYZKALLER: /vol/myfuzz-variants/v6.6.100.E-/syzkaller
      OUT_ROOT: /vol2/myfuzz-E-
    command: |
      bash -c '
        export suffix=$$(cat /proc/sys/kernel/random/uuid | cut -d- -f1)
        export WORKDIR=$$OUT_ROOT/out-$$suffix
        mkdir -p $$WORKDIR &&
        cat $$MYFUZZ/configs/fuzz/linux.cfg | envsubst > /home/linux.cfg &&
        timeout -s KILL 24h $$SYZKALLER/bin/syz-manager -config /home/linux.cfg > $$WORKDIR/myfuzz.E-.log 2>&1
      '

  myfuzz-R-:
    <<: *base
    image: myfuzz:latest
    environment:
      <<: *env
      SYZKALLER: /vol/myfuzz-variants/v6.6.100.R-/syzkaller
      OUT_ROOT: /vol2/myfuzz-R-
    command: |
      bash -c '
        export suffix=$$(cat /proc/sys/kernel/random/uuid | cut -d- -f1)
        export WORKDIR=$$OUT_ROOT/out-$$suffix
        mkdir -p $$WORKDIR &&
        cat $$MYFUZZ/configs/fuzz/linux.cfg | envsubst > /home/linux.cfg &&
        timeout -s KILL 24h $$SYZKALLER/bin/syz-manager -config /home/linux.cfg > $$WORKDIR/myfuzz.R-.log 2>&1
      '

  myfuzz-RE-:
    <<: *base
    image: myfuzz:latest
    environment:
      <<: *env
      SYZKALLER: /vol/myfuzz-variants/v6.6.100.RE-/syzkaller
      OUT_ROOT: /vol2/myfuzz-RE-
    command: |
      bash -c '
        export suffix=$$(cat /proc/sys/kernel/random/uuid | cut -d- -f1)
        export WORKDIR=$$OUT_ROOT/out-$$suffix
        mkdir -p $$WORKDIR &&
        cat $$MYFUZZ/configs/fuzz/linux.cfg | envsubst > /home/linux.cfg &&
        timeout -s KILL 24h $$SYZKALLER/bin/syz-manager -config /home/linux.cfg > $$WORKDIR/myfuzz.RE-.log 2>&1
      '