# Docker Compose file for fuzzing android kernel.
# Please modify the corresponding paths before use.

x-fuzz-base: &fuzz-base
  image: syzmeta:latest
  privileged: true
  network_mode: host
  volumes:
    # Setting your mounts
    - xxx:/vol
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro

services:
  run-cvd:
    <<: *fuzz-base
    cpuset: "0-15"
    environment:
      - KERNEL=/vol/android/common-android13-5.10/dist
      - IMAGE=/vol/android/android13
      - TARGET=aosp_cf_x86_64_phone-userdebug
    command: >
      bash -c "
        /vol/SyzMeta/scripts/android/run-cvd.sh -i $$IMAGE -k $$KERNEL/bzImage -t $$TARGET -n 8 &&
        LAUNCH_CVD_PID=$(pgrep -f launch_cvd) &&
        timeout -s KILL 24h tail --pid=$$LAUNCH_CVD_PID -f /dev/null
      "

  SyzMeta-000:
    # ^^^^^^^ If you copy this service, please change service's name
    <<: *fuzz-base
    cpuset: "0-1" # <- If you copy this service, please change cpuset
    depends_on:
      - run-cvd
    environment:
      - SERVADDR=127.0.0.1:50000 # <- If you copy this service, please change serve address since we use host networking
      - WORKDIR=/vol/workdir/SyzMeta/out-000 # <- If you copy this service, please change workdir to avoid conflict
      - KERNEL=/vol/android/common-android13-5.10/dist
      - SYZKALLER=/vol/SyzMeta/syzkaller
      - DEVICE=0.0.0.0:6520 # <- If you copy this service, please change device code since we use host networking
    command: >
      bash -c "
        cat /vol/SyzMeta/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        timeout -s KILL 24h $$SYZKALLER/bin/syz-manager -config /home/android.cfg > $$WORKDIR/SyzMeta.log 2>&1
      "

  syzkaller-000:
    <<: *fuzz-base
    cpuset: "8-9"
    depends_on:
      - run-cvd
    environment:
      - SERVADDR=127.0.0.1:50004 # <- If you copy this service, please change serve address since we use host networking
      - WORKDIR=/vol/workdir/syzkaller/out-000 # <- If you copy this service, please change workdir to avoid conflict
      - KERNEL=/vol/android/common-android13-5.10/dist
      - SYZKALLER=/vol/syzkaller
      - DEVICE=0.0.0.0:6524 # <- If you copy this service, please change device code since we use host networking
    command: >
      bash -c "
        cat /vol/SyzMeta/configs/fuzz/android.cfg | envsubst > /home/android.cfg &&
        mkdir -p $$WORKDIR &&
        timeout -s KILL 24h $$SYZKALLER/bin/syz-manager -config /home/android.cfg > $$WORKDIR/syzkaller.log 2>&1
      "
