import os
import argparse
import subprocess

from os.path import *
from utils import *


def repro(args: argparse.Namespace):
    """复现syzkaller-based fuzzer保存的crashes

    Parameters
    ----------
    args : argparse.Namespace
        命令行参数
    """
    crash_logs = args.crash
    repro_bin = args.bin
    config = args.config
    start_time = time.time()
    succ, fail = list(), list()

    # 遍历所有输入的log文件, 将其作为syz-repro的输入, 尝试复现crash
    for crash_log in crash_logs:
        fn = basename(crash_log)
        ACTF(f"Reproducing {crash_log}...")
        res = subprocess.run(
            [
                repro_bin,
                f"-config={config}",
                "-output=" + join(dirname(crash_log), f"repro.{fn}.txt"),
                "-crepro=" + join(dirname(crash_log), f"repro.{fn}.c"),
                crash_log,
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        if res.returncode != 0:
            fail.append(crash_log)
            BADF(f"Reproduce {crash_log} failed!")
            with open(f"{crash_log}.out", "w") as f:
                f.write(res.stdout.decode())
            with open(f"{crash_log}.err", "w") as f:
                f.write(res.stderr.decode())
        else:
            succ.append(crash_log)
            OKF(f"Reproduce {crash_log} success!")
        WARNF(f"Time cost: {time.time() - start_time:.2f}s")

    with open("repro.log", "w") as f:
        f.write("Success:\n")
        for s in succ:
            f.write(f"{s}\n")
        f.write("\nFailed:\n")
        for s in fail:
            f.write(f"{s}\n")
    OKF(f"Reproduce finished! Success: {len(succ)}, Failed: {len(fail)}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Process crashes generated by syzkaller-based fuzzer.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # Subcommand for reproducing
    repro_parser = subparsers.add_parser("repro", help="Reproduce crashes")
    repro_parser.add_argument("--crash", nargs="+", type=str, required=True, help="Parent directory that contain crashes folder(s)")
    repro_parser.add_argument("--bin", type=str, required=True, help="Path to the syz-repro binary")
    repro_parser.add_argument("--config", type=str, required=True, help="Config file for syz-repro")
    repro_parser.set_defaults(func=repro)

    # Parse the arguments
    args = parser.parse_args()
    args.func(args)
