"""
Author       : Radon
Date         : 2025-06-11 06:52:52
LastEditors  : Radon
LastEditTime : 2025-06-14 04:11:04
Description  : 改进Zhang等人提出方法, 识别内核中的MR
               论文名称: Can large language models discover metamorphic relations? A large-scale empirical study
               发表源: SANER 2025
"""

import argparse
import json
import sys
import os

from os.path import abspath, dirname, join, exists

# 添加tools/syz-meta/src目录到sys.path中, 以便导入其他模块
pa = dirname(dirname(abspath(__file__)))
sys.path.append(pa)
import MRImpl

from typing import Tuple
from wrappers.openai import OpenAI
from utils import *


def validate(mr_code: str, syzkaller: str) -> Tuple[int, str, str]:
    """验证LLM生成的代码是否可作为pseudo-syscall集成至syzkaller

    Parameters
    ----------
    mr_code : str
        LLM生成的MR实现代码
    syzkaller : str
        syzkaller的路径

    Returns
    -------
    bool
        如果MR代码可以合并至syzkaller, 返回True; 否则返回False
    """
    func = "syz_mr"
    params = MRImpl.get_params(mr_code, func, input_file=False)
    syzlang = "syz_mr(" + ",".join([f"{param} int32" for param in params]) + ")"
    return MRImpl.add_pseudo_syscall(syzkaller, mr_code, syzlang, func)


def main(config: dict):
    """使用Zhang et al. (SANER 2025)提出的方法识别内核的蜕变关系。

    Parameters
    ----------
    args : argparse.Namespace
        命令行参数
    """
    # 读取系统提示和用户提示
    sys_prompt = str()
    with open(config["prompts"]["system"], "r") as f:
        sys_prompt = f.read()
    usr_prompts = list()
    for fn in config["prompts"]["user"]:
        with open(fn, "r") as f:
            usr_prompts.append(f.read())

    # 根据配置文件初始化llm对象
    llm_obj = OpenAI(
        base_url=config["base_url"],
        api_key=config["api_key"],
        model=config["model"],
        temperature=config["temperature"],
        stream=config["stream"],
    )
    llm_obj.set_sys_prompt(sys_prompt)

    # 读取规格说明的内容
    spec = str()
    with open(config["specification"], "r") as f:
        spec = f.read()
    spec = f"```\n{spec}\n```"

    # 与LLM交互, 让LLM识别内核的蜕变关系, 并基于验证结果反馈给LLM, 提升MR的质量
    index = 0
    gen_succ = False
    iter = 0
    err_msgs = str()
    while iter < config["max_iter"]:
        ACTF(f"Iter {iter + 1}: Prompting {config["model"]} to generate encoded-MRs ...")
        prompt = usr_prompts[index]
        prompt = prompt.replace("[specification]", spec)
        prompt = prompt.replace("[Errors reported by syzkaller]", err_msgs)
        response = llm_obj.chat(prompt)
        mr_code = get_first_code_block(response, {"c"})
        mr_code = mr_code.lstrip("`c\n").rstrip("`\n")
        if len(mr_code) == 0:
            FATAL("No code block found in the response. Please check the prompt and try again.")
        valid_res, stderr, stdout = validate(mr_code, config["syzkaller"])
        err_msgs = stderr + "\n\n" + stdout
        iter += 1
        index += 1
        if index >= len(usr_prompts):
            index -= 1
        if not valid_res:
            gen_succ = True
            break
        WARNF("Failed to integreate encoded-MR into syzkaller, retrying ...")

    # 保存mr_code(如果生成成功)和LLM交互记录
    out_dir = config["output"]
    if not exists(out_dir):
        os.makedirs(out_dir)
    with open(join(out_dir, "valid_res"), "w") as f:
        f.write(str(gen_succ))
    if gen_succ:
        OKF("Generate encoded-MR successfully.")
        mr_code = f"// Code generated by {config["model"]} after {iter + 1} iterations\n" + mr_code
        with open(join(out_dir, "mr.h"), "w") as f:
            f.write(mr_code)
    else:
        BADF("Generate encoded-MR failed.")
    llm_obj.save_messages(join(out_dir, "messages.json"))
    llm_obj.save_messages(join(out_dir, "messages.md"))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Baseline method for MR identification, refer to the paper published by Zhang et al. in SANER 2025.")
    parser.add_argument("--config", type=str, required=True, help="Path to the configuration file.")
    args = parser.parse_args()
    config = dict()
    with open(args.config) as f:
        config = json.load(f)
    main(config)
