import os
import sys
import argparse
import shutil

import pandas as pd

from os.path import join, basename, dirname, abspath

sys.path.append(join(dirname(abspath(__file__)), ".."))
from utils import *


def filter_bugs(args: argparse.Namespace):
    """Filter specified bugs and copy them to a new directory

    Parameters
    ----------
    args : argparse.Namespace
        Command line arguments
    """
    indir, hashes, outdir = args.input, set(args.hashes), args.output
    cnt = 0
    for root, dirs, _ in os.walk(indir):
        if basename(root) != "crashes":
            continue
        for dir in dirs:
            if dir not in hashes:
                continue
            src = join(root, dir)
            dst = join(outdir, src.removeprefix(indir).lstrip(os.sep))
            os.makedirs(dst, exist_ok=True)
            shutil.copytree(src, dst, dirs_exist_ok=True)
            cnt += 1
    OKF(f"Copied {cnt} folder(s) from {indir} to {outdir}.")


def get_all_crash_info(path: str) -> list[tuple[str, str]]:
    """获取指定目录下所有crash的信息, 包含描述和hash

    Parameters
    ----------
    path : str
        要遍历的目录

    Returns
    -------
    list[tuple[str]]
        所有crash的描述和对应的hash构成的元组列表
    """
    crash_info = list()
    for root, dirs, _ in os.walk(path):
        if os.path.basename(root) != "crashes":
            continue
        for dir in dirs:
            hash = dir
            with open(join(root, dir, "description"), "r") as f:
                desc = f.read().strip()
            crash_info.append((desc, hash))
    return crash_info


def merge(args: argparse.Namespace):
    """合并syzkaller-based fuzzer保存的crashes

    Parameters
    ----------
    args : argparse.Namespace
        命令行参数
    """
    fuzzers = args.fuzzers
    crash_dict = dict()  # { "kernel bug desc ...": { "hash": "123abc...", "fuzzers": { "fuzzer1", ... } } }
    for fuzzer in fuzzers:
        crash_info = get_all_crash_info(fuzzer)
        for desc, hash in crash_info:
            if desc not in crash_dict:
                crash_dict[desc] = dict()
                crash_dict[desc]["hash"] = hash
                crash_dict[desc]["fuzzers"] = set()
            crash_dict[desc]["fuzzers"].add(fuzzer)

    # 以CSV的形式打印合并结果
    print('Hash,Crash Description,"' + '","'.join(fuzzers) + '"')
    for desc, subdict in crash_dict.items():
        hash = subdict["hash"]
        exposed_fuzzers = subdict["fuzzers"]
        line = f'{hash},"{desc}",' + ",".join("TRUE" if fuzzer in exposed_fuzzers else "FALSE" for fuzzer in fuzzers)
        print(line)


def mergenew(args: argparse.Namespace):
    """合并新的crash信息

    Parameters
    ----------
    args : argparse.Namespace
        命令行参数
    """
    # Read excel
    excel = args.excel
    df = pd.read_excel(excel, sheet_name="Bugs", header=2, engine="calamine")  # 读取存储bug信息的sheet
    new_bug_df = df[df["new"] == True]

    # Prepare table data
    vis = set()
    data_list = list()
    for _, row in new_bug_df.iterrows():
        # Prevent duplicate accessing
        desc = row["desc"]
        if desc in vis:
            continue
        vis.add(desc)

        # Collect kernel versions and syzkaller/SyzMeta exposure
        vers = new_bug_df[new_bug_df["desc"] == desc]["kernel version"].unique().tolist()
        syzmeta_vers = new_bug_df[(new_bug_df["desc"] == desc) & (new_bug_df["SyzMeta exposed"] == True)]["kernel version"].unique().tolist()
        syzkaller_vers = new_bug_df[(new_bug_df["desc"] == desc) & (new_bug_df["syzkaller exposed"] == True)]["kernel version"].unique().tolist()
        vers.sort()
        syzmeta_vers.sort()
        syzkaller_vers.sort()
        data_list.append(
            {
                "desc": desc,
                "kernel version": ", ".join(vers),
                "SyzMeta": ", ".join(syzmeta_vers),
                "syzkaller": ", ".join(syzkaller_vers),
            }
        )

    # Output as CSV
    data_df = pd.DataFrame(data_list)
    data_df.to_csv(sys.stdout, index=False)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Process crashes generated by syzkaller-based fuzzer.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # Subcommand for filtering specified bugs
    filter_parser = subparsers.add_parser("filter", help="Filter specified bugs and copy them to a new directory")
    filter_parser.add_argument("--input", type=str, required=True, help="Input directory containing crashes")
    filter_parser.add_argument("--hashes", nargs="+", type=str, required=True, help="List of hashes to filter")
    filter_parser.add_argument("--output", type=str, required=True, help="Output directory to save filtered crashes")
    filter_parser.set_defaults(func=filter_bugs)

    # Subcommand for merging
    merge_parser = subparsers.add_parser("merge", help="Merge crashes")
    merge_parser.add_argument("--fuzzers", nargs="+", type=str, required=True, help="List of fuzzers to merge crashes from")
    merge_parser.set_defaults(func=merge)

    # Subcommand for mergenew
    mergenew_parser = subparsers.add_parser("mergenew", help="Merge new crashes")
    mergenew_parser.add_argument("--excel", type=str, required=True, help="Path to the Excel file containing new crashes")
    mergenew_parser.set_defaults(func=mergenew)

    # Parse the arguments
    args = parser.parse_args()
    args.func(args)
